Expand travis config

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,2 +1,41 @@
 language: haskell
 sudo: false
+env:
+  - CABALVER=1.18 GHCVER=7.4.2
+  - CABALVER=1.18 GHCVER=7.6.3
+  - CABALVER=1.20 GHCVER=7.8.3
+  - CABALVER=1.22 GHCVER=7.10.3
+  - CABALVER=1.24 GHCVER=8.0.2
+  - CABALVER=head GHCVER=head
+
+matrix:
+  allow_failures:
+    - env: CABALVER=head GHCVER=head
+
+before_install:
+  - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
+  - travis_retry sudo apt-get update
+  - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER
+  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
+
+install:
+  - cabal --version
+  - ghc --version
+  - travis_retry cabal update
+
+script:
+ - cabal install --only-dependencies
+ - cabal configure -v2 --enable-tests
+ - cabal build
+ - cabal check
+ - cabal test
+ - cabal sdist
+ - cabal haddock
+ - export SRC_TGZ=$(cabal info . | awk '{print $2 ".tar.gz";exit}') ;
+   cd dist/;
+   if [ -f "$SRC_TGZ" ]; then
+      cabal install --force-reinstalls "$SRC_TGZ";
+   else
+      echo "expected '$SRC_TGZ' not found";
+      exit 1;
+   fi
